config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :todos, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :password, presence: false

  has_many :todos

  def valid_password?(password)
    if password.blank?
      true
    else
      super
    end
  end

  def password_required?
    new_record? ? false : super
  end

  def remember_value
    self.remember_token ||= Devise.friendly_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    if @todo.save
      redirect_to todos_path(@todo)
    else
      render :new
    end
  end

  def show
    @todo = Todo.find(params[:id])
    @user = @todo.user
  end

  def index
    @todos = Todo.all.order(created_at: :desc)
  end

 private

  def todo_params
    params.require(:todo).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Pages#home</h1>


  <%= link_to "See all", todos_path  %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li><%= link_to "New", new_todo_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/todos/index.html.erb
 <div class="container">
  <p> TODOS LIST</p>
  <p><input type="checkbox" id="all-todos" name="all-todos">
  <label for="all-todos">Check all</label></p>
  <ol>
    <% @todos.each do |todo| %>
      <input type="checkbox" id="todos" name="todos">
      <label for="todos"><%= todo.title %></label>
      <ul>
        <li><%= todo.description %></li>
        <li><%= todo.duedate %></li>
      </ul>
    <% end %>
  </ol>
</div>

app/views/todos/new.html.erb
<div class="container">
    <div>
      <%= simple_form_for [@user, @todo] do |f| %>
        <%= f.input :title, :label=> "Title of your todo", placeholder: "What do you have to do ?", input_html: { class: "input-bar"}, wrapper_html: { class: "label-text"}, required: true %>
        <%= f.input :description, :label=> "Give more details :", placeholder:"almond milk, this brand... ",input_html: { class: "input-bar"}, wrapper_html: { class: "label-text"} %>
        <%= f.input :duedate, :label=> "Due date", input_html: { min: '0', step: 'any', class: "input-bar"}, wrapper_html: { class: "label-text"} %>

        <div class="btn-center">
          <% if @todo.id %>
            <%= f.submit "Edit Todo", class: "btn-other btn-ghost2 btn-form" %>
          <% else %>
            <%= f.submit "Add Todo", class: "btn-other btn-ghost2 btn-form" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>